### ISSUE TITLE
Chroma 29 for OEPL

### ISSUE THREAD

**Issue by LeftPinkie** [skiphansen/dmitrygr-einkTags#3]
Hi Skip,

I just purchased a bunch of Chroma 29 from eBay. I was wondering if you could help me flash the OpenEPaperLink FW onto these tags. I also live in SoCal (LA).

**Comment by skiphansen** [comment]
Wow!  I thought almost everyone was over seas!

Yes we can do that ... send me a PM via discord and I'll send you contact info.

**Comment by LeftPinkie** [comment]
> send me a PM via discord

I don't have discord. You can email me at leftpinkie{at}ortracon{dot}com
